# This is a basic workflow to help you get started with Actions

name: TestIssues
  
on:
  issues:
    types:
      - labeled


jobs:
  add-comment:
    if: github.event.label.name == 'request to update cache'
    runs-on: ubuntu-latest
    permissions:
      issues: write
    steps:
      - name: View issue information
        run: |
          echo "Issue title: ${{ github.event.issue.title }}"
          echo "Issue body: ${{ github.event.issue.body }}"

